// <auto-generated/>

global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Threading;
global using global::System.Threading.Tasks;

using System.Reflection;
using System.Resources;

#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif

[assembly: AssemblyCompany("Fluxera Software Development GmbH")]
[assembly: AssemblyProduct("Fluxera Software Foundation")]
[assembly: AssemblyCopyright("Copyright © 2014-2021 Fluxera Software Development GmbH. All rights reserved.")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: AssemblyVersion("11.0.0")]
[assembly: AssemblyFileVersion("11.0.0")]
[assembly: AssemblyInformationalVersion("11.0.0")]
